language: python

python: "2.7"

env:
  - STREAM_LOCKER_TARGET='chrome'
  - STREAM_LOCKER_TARGET='firefox'

install:
  - sudo pip install -U pip
  - pip install -U GitPython github3.py
  - npm i -g web-ext

script:
  - export GH_RELEASE_BRANCH='master' GH_RELEASE_BASENAME='Stream Locker'
  - ./build.py --release --deploy "$STREAM_LOCKER_TARGET"

cache:
  directories:
    - $HOME/.cache/pip
    - node_modules

notifications:
  email: false
