language: python

python: "2.7"

env:
  - STREAM_LOCKER_TARGET='chrome'
  - STREAM_LOCKER_TARGET='firefox'

install:
  - sudo pip install --upgrade pip
  - pip install GitPython github3.py
  - npm install -g web-ext

script:
  - export GH_RELEASE_BRANCH='master' GH_RELEASE_BASENAME='Stream Locker'
  - ./build.py --release "$STREAM_LOCKER_TARGET"

notifications:
  email: false
